# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  
  pod 'Alamofire'
  pod 'OAuth3A', :git => 'https://github.com/mevansjr/OAuth3A'

end
